# Generated by Django 4.2 on 2023-04-18 21:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_alter_shop_user_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
