# Generated by Django 4.2 on 2023-04-19 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='avatar',
            field=models.ImageField(null=True, upload_to='shops/%Y/%m/'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'shop')},
        ),
    ]
