# Generated by Django 4.2 on 2023-04-22 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0008_review_comment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set(),
        ),
    ]
